version: '2'
services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        links:
            - db

    db:
        image: "postgres:${POSTGRES_VERSION}"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: hunter2
    redis:
        skfkg
    celery_daemon:
        sfdfg